from src.data_modules.CasiaDataModule import CasiaDataModule
from src.data_modules.CIFAR10DataModule import CIFAR10DataModule
from src.data_modules.FashionMNISTDataModule import FashionMNISTDataModule
from src.data_modules.MNISTDataModule import MNISTDataModule
from src.data_modules.CUB200DataModule import CUB200DataModule
